// Package monid lists Monid's tools (monid.ai, "OpenRouter for agent tools")
// as one of Algebra's catalogs, and holds a client for Monid's API.
//
// Monid sells some 600 endpoints from two dozen providers (Exa, Apify,
// People Data Labs, DataForSEO, Surf, MiniMax, ...) paid from a prepaid Monid
// balance, not over x402. Algebra can't pay them on Solana yet, so they are
// listed for discovery and comparison only: each endpoint says it is billed to
// a Monid balance and is never a routing candidate. Paying them (a Monid
// account rail, or cards through Stripe) is future work.
//
// The listing is snapshot.json, generated by cmd/monid-import from Monid's
// open-source connector repository (github.com/monid-ai/monid), so it needs no
// account. Prices are kept where the connector states them in US dollars;
// the rest bill in vendor credits Monid converts on its side.
package monid

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"math"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/project-algebra/algebra/internal/domain/routing"
	"github.com/project-algebra/algebra/providers/catalog"
)

// Source is the catalog's name in listings; Prefix starts its provider IDs.
const (
	Source = "monid"
	Prefix = "monid:"
)

// NotPayable is why no Monid endpoint can be called through Algebra today.
const NotPayable = "billed to a prepaid Monid balance, not over x402: Algebra can't pay it on Solana yet"

//go:embed snapshot.json
var snapshotJSON []byte

type rawEndpoint struct {
	Path        string   `json:"path"`
	Method      string   `json:"method"`
	Name        string   `json:"name"`
	Summary     string   `json:"summary"`
	Categories  []string `json:"categories"`
	PriceKind   string   `json:"price_kind"`
	PriceUSD    float64  `json:"price_usd"`
	PriceUnit   string   `json:"price_unit"`
	ConnectorID string   `json:"connector_id"`
}

type rawProvider struct {
	Slug       string        `json:"slug"`
	Name       string        `json:"name"`
	Summary    string        `json:"summary"`
	Homepage   string        `json:"homepage"`
	Categories []string      `json:"categories"`
	CreditUnit string        `json:"credit_unit"`
	Endpoints  []rawEndpoint `json:"endpoints"`
}

type rawSnapshot struct {
	Source    string        `json:"source"`
	Generated time.Time     `json:"generated_at"`
	Providers []rawProvider `json:"providers"`
}

// Catalog is Monid's tools as a catalog.Source.
type Catalog struct {
	once      sync.Once
	err       error
	providers []catalog.Provider
	details   map[string]*catalog.Detail
	generated time.Time
}

var _ catalog.Source = (*Catalog)(nil)

// New builds the catalog from the embedded snapshot.
func New() *Catalog { return &Catalog{} }

func (c *Catalog) Name() string   { return Source }
func (c *Catalog) Prefix() string { return Prefix }

// categoryOf maps Monid's categories onto the words the other catalogs use.
func categoryOf(cats []string) string {
	for _, k := range cats {
		switch k {
		case "web-search", "ai-search", "news-search", "seo":
			return "search"
		case "web-extraction", "web-scraping", "company-enrichment", "people-enrichment", "funding-data", "linkedin", "geo":
			return "data"
		case "video-generation", "image-generation", "music-generation", "3d-generation", "speech":
			return "media"
		case "token-prices", "onchain-data", "prediction-markets":
			return "finance"
		case "sms", "agentic-phone":
			return "messaging"
		}
	}
	return "other"
}

// micro turns a USD price into micro-dollars, rounding up so a price is never
// shown lower than it is.
func micro(usd float64) int64 {
	if usd <= 0 || math.IsNaN(usd) || math.IsInf(usd, 0) {
		return 0
	}
	return int64(math.Ceil(usd*1_000_000 - 1e-9))
}

func priceText(e rawEndpoint) string {
	switch {
	case e.PriceKind == "FREE":
		return "free"
	case e.PriceUSD <= 0:
		return "priced by Monid (vendor credits)"
	case e.PriceUnit != "":
		return fmt.Sprintf("$%s per %s", trimFloat(e.PriceUSD), e.PriceUnit)
	}
	return fmt.Sprintf("$%s per call", trimFloat(e.PriceUSD))
}

func trimFloat(v float64) string {
	s := fmt.Sprintf("%.6f", v)
	return strings.TrimRight(strings.TrimRight(s, "0"), ".")
}

func (c *Catalog) load() error {
	c.once.Do(func() {
		var snap rawSnapshot
		if err := json.Unmarshal(snapshotJSON, &snap); err != nil {
			c.err = fmt.Errorf("monid: the embedded snapshot is unreadable: %w", err)
			return
		}
		c.generated, c.details = snap.Generated, map[string]*catalog.Detail{}
		for _, rp := range snap.Providers {
			p := catalog.Provider{
				ID: Prefix + rp.Slug, FQN: rp.Slug, Name: catalog.CleanText(rp.Name, catalog.MaxTitle),
				Description: catalog.CleanText(rp.Summary, catalog.MaxDescription), Category: categoryOf(rp.Categories),
				ServiceURL: "https://api.monid.ai/v1", Host: "api.monid.ai", Metered: true,
				Currency: "USD", PageURL: "https://monid.ai/tools/" + rp.Slug, Website: rp.Homepage,
				Networks: []string{}, Source: Source, Billing: "monid-balance",
			}
			d := &catalog.Detail{Provider: p, FetchedAt: snap.Generated}
			for _, re := range rp.Endpoints {
				price := micro(re.PriceUSD)
				if price > 0 && (p.MinPriceMinor == 0 || price < p.MinPriceMinor) {
					p.MinPriceMinor = price
				}
				p.MaxPriceMinor = max(p.MaxPriceMinor, price)
				p.FreeTier = p.FreeTier || re.PriceKind == "FREE"
				desc := re.Summary
				if desc == "" {
					desc = re.Name
				}
				d.Endpoints = append(d.Endpoints, catalog.Endpoint{
					Capability: catalog.CapabilityID("monid."+catalog.Slug(rp.Slug, 24), re.Method, re.Path),
					Method:     re.Method, Path: re.Path, URL: "https://monid.ai/tools/" + rp.Slug,
					Pricing: priceText(re), PriceMinor: price, Free: re.PriceKind == "FREE",
					Description: catalog.CleanText(desc, catalog.MaxDescription), Callable: false, Reason: NotPayable,
				})
			}
			p.EndpointCount = len(d.Endpoints)
			d.Provider = p
			c.providers = append(c.providers, p)
			c.details[p.ID] = d
		}
		slices.SortFunc(c.providers, func(a, b catalog.Provider) int { return strings.Compare(a.Name, b.Name) })
	})
	return c.err
}

// List returns Monid's providers. Monid bills off chain, so a listing for a
// Solana network leaves them out unless Monid itself was asked for.
func (c *Catalog) List(_ context.Context, f catalog.Filter) (*catalog.Listing, error) {
	if err := c.load(); err != nil {
		return nil, err
	}
	out := &catalog.Listing{Source: Source, GeneratedAt: c.generated, FetchedAt: c.generated, Categories: []catalog.Category{}, Providers: []catalog.Provider{}}
	if f.Network != "" && !strings.EqualFold(f.Source, Source) {
		return out, nil
	}
	nf := f
	nf.Network = ""
	counts := map[string]int{}
	for _, p := range c.providers {
		if !nf.Matches(p) {
			continue
		}
		out.Providers = append(out.Providers, p)
		counts[p.Category]++
	}
	for name, n := range counts {
		out.Categories = append(out.Categories, catalog.Category{Name: name, Count: n})
	}
	out.Total, out.Count = len(out.Providers), len(out.Providers)
	return out, nil
}

// Detail returns a provider with its endpoints, by ID ("monid:exa") or slug.
func (c *Catalog) Detail(_ context.Context, id string) (*catalog.Detail, error) {
	if err := c.load(); err != nil {
		return nil, err
	}
	id = strings.ToLower(strings.TrimSpace(id))
	if !strings.HasPrefix(id, Prefix) {
		id = Prefix + id
	}
	d, ok := c.details[id]
	if !ok {
		return nil, catalog.ErrNotFound
	}
	cp := *d
	cp.Endpoints = slices.Clone(d.Endpoints)
	return &cp, nil
}

// CandidatesFor and ForCapability return nothing: no Monid endpoint is a
// routing candidate until Algebra can pay Monid.
func (c *Catalog) CandidatesFor(context.Context, string, string) ([]routing.Candidate, error) {
	return nil, nil
}

func (c *Catalog) ForCapability(context.Context, string) ([]routing.Candidate, error) {
	return nil, catalog.ErrNotFound
}
